---
title: "Proposal: Victorian Motor Vehicle Accidents"
author: "Bruno Quevedo, Priscilla Soenario"
date: "01/09/2019"
output: html_document
---
## Background
_Rationale and stakeholders_
VicRoads is the sate government body that manages and regulates the main road network within the Victorian state, with a goal to create a smarter and safer road network across the state. Along with delivering road safety initiatives, VicRoads provides registration and licensing services for all motor vehicles.

One of their strategies to manage the safety of road users is their "Towards Zero" campaign which aims to reduce road fatalities to below 200 per annum by 2020.
Over the past 5 years...

The campaign currently uses....... to tackle road safety issues.

Another factor to consider towards achieving this goal


## Proposed Research Questions
We are proposing the following research questions to further investigate factors contributing towards road crashes.
1. How do different weather conditions 
2. 
3. 


## Data Sets
_Range of datasets examined, chosen for the analysi. How datasets were merged. Is granularity of data sufficient to answer research questions_


## Regression Modelling
_Regression modelling techniques to be employed_


## Issues
_issues anticipated may arise_



## Appendix
_code samples demonstrating the data acquisition and merger processes that you have used to date_


